export const JOB_CARDS = [
  {
    title: 'Visual Designer',
    status: true,
    applicants: 24,
    location: 'Lagos, Nigeria',
    workType: 'remote',
    entryLevel: true,
    updatedAt: '2 hours ago',
  },
  {
    title: 'Software Engineer',
    status: true,
    applicants: 30,
    location: 'New York, USA',
    workType: 'remote',
    entryLevel: false,
    updatedAt: '1 day ago',
  },
  {
    title: 'Marketing Manager',
    status: false,
    applicants: 15,
    location: 'London, UK',
    workType: 'hybrid',
    entryLevel: false,
    updatedAt: '3 days ago',
  },
  {
    title: 'Data Analyst',
    status: true,
    applicants: 10,
    location: 'Paris, France',
    workType: 'full time',
    entryLevel: true,
    updatedAt: '1 week ago',
  },
];

export const COMPANY_DASHBOARD_CARDS = [
  {
    title: 'Active Job Posting',
    icon: '/assets/dashboard/icons/briefcase.svg',
    description: 'Active Jobs',
    color: 'var(--color-accent-3-dark)',
    iconBg: 'var(--color-accent-3)',
    count: 2,
  },
  {
    title: 'Total Applicants',
    icon: '/assets/dashboard/icons/people.svg',
    description: 'New Applicants',
    color: 'var(--color-secondary)',
    iconBg: 'var(--color-light-blue)',
    count: 0,
  },
  {
    title: 'Hires Completed',
    icon: '/assets/dashboard/icons/profile-tick.svg',
    description: 'Hires',
    color: 'var(--color-accent-pink)',
    iconBg: 'var(--color-accent-pink-light)',
    count: 0,
  },
];

export const TALENT_DASHBOARD_CARDS = [
  {
    title: 'Job Applications',
    icon: '/assets/dashboard/icons/briefcase.svg',
    description: 'Applications Sent',
    color: 'var(--color-accent-3-dark)',
    iconBg: 'var(--color-accent-3)',
    count: 0,
  },
  {
    title: 'Profile Views',
    icon: '/assets/dashboard/icons/people.svg',
    description: 'Views this month',
    color: 'var(--color-secondary)',
    iconBg: 'var(--color-light-blue)',
    count: 0,
  },
  {
    title: 'Save Jobs',
    icon: '/assets/dashboard/icons/profile-tick.svg',
    description: 'Jobs Saved',
    color: 'var(--color-accent-pink)',
    iconBg: 'var(--color-accent-pink-light)',
    count: 0,
  },
];

export const SUGGESTED_SKILLS = [
  'Proficiency in Figma, Adobe XD, or Sketch',
  'Strong understanding of UX principles & design systems',
  'Experience creating responsive layouts for web and mobile',
  'Knowledge of HTML/CSS (bonus)',
];

export const JOB_CATEGORIES = [
  'Design',
  'Engineering',
  'Marketing',
  'Video and Animation',
  'Music',
  'Art',
  'Social Media',
];

export const countries = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Ireland',
  'Portugal',
  'Poland',
  'Czech Republic',
  'Japan',
  'South Korea',
  'China',
  'India',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'United Arab Emirates',
  'Saudi Arabia',
  'Israel',
  'Turkey',
  'Brazil',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Egypt',
  'New Zealand',
];

export const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'London',
  'Manchester',
  'Birmingham',
  'Leeds',
  'Glasgow',
  'Toronto',
  'Vancouver',
  'Montreal',
  'Calgary',
  'Ottawa',
  'Sydney',
  'Melbourne',
  'Brisbane',
  'Perth',
  'Adelaide',
  'Berlin',
  'Munich',
  'Hamburg',
  'Frankfurt',
  'Cologne',
  'Paris',
  'Lyon',
  'Marseille',
  'Toulouse',
  'Nice',
  'Madrid',
  'Barcelona',
  'Valencia',
  'Seville',
  'Bilbao',
  'Rome',
  'Milan',
  'Naples',
  'Turin',
  'Florence',
  'Amsterdam',
  'Rotterdam',
  'The Hague',
  'Utrecht',
  'Eindhoven',
  'Brussels',
  'Antwerp',
  'Ghent',
  'Zurich',
  'Geneva',
  'Basel',
  'Vienna',
  'Stockholm',
  'Oslo',
  'Copenhagen',
  'Helsinki',
  'Dublin',
  'Lisbon',
  'Porto',
  'Warsaw',
  'Krakow',
  'Prague',
  'Tokyo',
  'Osaka',
  'Seoul',
  'Busan',
  'Shanghai',
  'Beijing',
  'Shenzhen',
  'Guangzhou',
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Singapore',
  'Kuala Lumpur',
  'Bangkok',
  'Jakarta',
  'Manila',
  'Ho Chi Minh City',
  'Dubai',
  'Abu Dhabi',
  'Riyadh',
  'Tel Aviv',
  'Istanbul',
  'São Paulo',
  'Rio de Janeiro',
  'Mexico City',
  'Buenos Aires',
  'Santiago',
  'Bogotá',
  'Cape Town',
  'Johannesburg',
  'Lagos',
  'Nairobi',
  'Cairo',
  'Auckland',
  'Wellington',
];

export const companyDashboardNavLinks = [
  { title: 'Active Jobs', value: '/active' },
  { title: 'Closed Jobs', value: '/closed' },
  { title: 'Drafts', value: '/drafts' },
];
