import type { Metadata } from 'next';
import { Bricolage_Grotesque } from 'next/font/google';
import './globals.css';

const brics = Bricolage_Grotesque({
  variable: '--font-bricolage',
});

export const metadata: Metadata = {
  title: 'HNG Portal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brics.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
