name: CI for PRs with Preview Deployment

on:
    pull_request:

permissions:
    contents: read
    pull-requests: write

jobs:

    ci:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                    pnpm-store-

            - name: Install dependencies
              run: CI=true pnpm install --frozen-lockfile

            - name: Lint
              run: CI=true pnpm lint

            - name: Build app
              run: CI=true pnpm build
